In [330]:
%matplotlib inline

In [331]:
import requests
import re
from fastai.text import *
import torch

In [332]:
book = requests.get('https://www.gutenberg.org/files/36/36-0.txt').text

In [333]:
start_iter = re.finditer('BOOK ONE', book)

In [334]:
next(start_iter)

<_sre.SRE_Match object; span=(1067, 1075), match='BOOK ONE'>

In [335]:
book[1067:]

'BOOK ONE.â\x80\x94THE COMING OF THE MARTIANS\r\n\r\n I. THE EVE OF THE WAR\r\n II. THE FALLING STAR.\r\n III. ON HORSELL COMMON.\r\n IV. THE CYLINDER OPENS.\r\n V. THE HEAT-RAY.\r\n VI. THE HEAT-RAY IN THE CHOBHAM ROAD.\r\n VII. HOW I REACHED HOME.\r\n VIII. FRIDAY NIGHT.\r\n IX. THE FIGHTING BEGINS.\r\n X. IN THE STORM.\r\n XI. AT THE WINDOW.\r\n XII. WHAT I SAW OF THE DESTRUCTION OF WEYBRIDGE AND SHEPPERTON.\r\n XIII. HOW I FELL IN WITH THE CURATE.\r\n XIV. IN LONDON.\r\n XV. WHAT HAD HAPPENED IN SURREY.\r\n XVI. THE EXODUS FROM LONDON.\r\n XVII. THE â\x80\x9cTHUNDER CHILDâ\x80\x9d.\r\n\r\n BOOK TWO.â\x80\x94THE EARTH UNDER THE MARTIANS\r\n\r\n I. UNDER FOOT.\r\n II. WHAT WE SAW FROM THE RUINED HOUSE.\r\n III. THE DAYS OF IMPRISONMENT.\r\n VI. THE DEATH OF THE CURATE.\r\n V. THE STILLNESS.\r\n VI. THE WORK OF FIFTEEN DAYS.\r\n VII. THE MAN ON PUTNEY HILL.\r\n VIII. DEAD LONDON.\r\n IX. WRECKAGE.\r\n X. THE EPILOGUE.\r\n\r\n\r\n\r\nBOOK ONE\r\n\r\nTHE COMING OF THE MARTIANS\r\n\r\n\r

In [336]:
next(start_iter)

<_sre.SRE_Match object; span=(1920, 1928), match='BOOK ONE'>

In [337]:
book[1920:]

'BOOK ONE\r\n\r\nTHE COMING OF THE MARTIANS\r\n\r\n\r\n\r\n\r\nI.\r\n\r\nTHE EVE OF THE WAR.\r\n\r\nNo one would have believed in the last years of the nineteenth century\r\nthat this world was being watched keenly and closely by intelligences\r\ngreater than manâ\x80\x99s and yet as mortal as his own; that as men busied\r\nthemselves about their various concerns they were scrutinised and\r\nstudied, perhaps almost as narrowly as a man with a microscope might\r\nscrutinise the transient creatures that swarm and multiply in a drop of\r\nwater. With infinite complacency men went to and fro over this globe\r\nabout their little affairs, serene in their assurance of their empire\r\nover matter. It is possible that the infusoria under the microscope do\r\nthe same. No one gave a thought to the older worlds of space as sources\r\nof human danger, or thought of them only to dismiss the idea of life\r\nupon them as impossible or improbable. It is curious to recall some of\r\nthe mental habits 

In [338]:
book = book[1920:]

In [339]:
end_iter = re.finditer("among the dead.", book)

In [340]:
next(end_iter)

<_sre.SRE_Match object; span=(64109, 64124), match='among the dead '>

In [341]:
book[:64125]

'BOOK ONE\r\n\r\nTHE COMING OF THE MARTIANS\r\n\r\n\r\n\r\n\r\nI.\r\n\r\nTHE EVE OF THE WAR.\r\n\r\nNo one would have believed in the last years of the nineteenth century\r\nthat this world was being watched keenly and closely by intelligences\r\ngreater than manâ\x80\x99s and yet as mortal as his own; that as men busied\r\nthemselves about their various concerns they were scrutinised and\r\nstudied, perhaps almost as narrowly as a man with a microscope might\r\nscrutinise the transient creatures that swarm and multiply in a drop of\r\nwater. With infinite complacency men went to and fro over this globe\r\nabout their little affairs, serene in their assurance of their empire\r\nover matter. It is possible that the infusoria under the microscope do\r\nthe same. No one gave a thought to the older worlds of space as sources\r\nof human danger, or thought of them only to dismiss the idea of life\r\nupon them as impossible or improbable. It is curious to recall some of\r\nthe mental habits 

In [342]:
next(end_iter)

<_sre.SRE_Match object; span=(345594, 345609), match='among the dead.'>

In [343]:
book[:345609]

'BOOK ONE\r\n\r\nTHE COMING OF THE MARTIANS\r\n\r\n\r\n\r\n\r\nI.\r\n\r\nTHE EVE OF THE WAR.\r\n\r\nNo one would have believed in the last years of the nineteenth century\r\nthat this world was being watched keenly and closely by intelligences\r\ngreater than manâ\x80\x99s and yet as mortal as his own; that as men busied\r\nthemselves about their various concerns they were scrutinised and\r\nstudied, perhaps almost as narrowly as a man with a microscope might\r\nscrutinise the transient creatures that swarm and multiply in a drop of\r\nwater. With infinite complacency men went to and fro over this globe\r\nabout their little affairs, serene in their assurance of their empire\r\nover matter. It is possible that the infusoria under the microscope do\r\nthe same. No one gave a thought to the older worlds of space as sources\r\nof human danger, or thought of them only to dismiss the idea of life\r\nupon them as impossible or improbable. It is curious to recall some of\r\nthe mental habits 

In [344]:
book = book[:345609]

In [345]:
book = re.sub(r'[\r\n]+', ' ', str(book))

In [346]:
book

'BOOK ONE THE COMING OF THE MARTIANS I. THE EVE OF THE WAR. No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than manâ\x80\x99s and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied, perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water. With infinite complacency men went to and fro over this globe about their little affairs, serene in their assurance of their empire over matter. It is possible that the infusoria under the microscope do the same. No one gave a thought to the older worlds of space as sources of human danger, or thought of them only to dismiss the idea of life upon them as impossible or improbable. It is curious to recall some of the mental habits of those departed days. At most terrestrial men fancied there might be other

In [347]:
tokens = [i.replace(',', '') for i in book.split('.')]

In [348]:
tokens

['BOOK ONE THE COMING OF THE MARTIANS I',
 ' THE EVE OF THE WAR',
 ' No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than manâ\x80\x99s and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water',
 ' With infinite complacency men went to and fro over this globe about their little affairs serene in their assurance of their empire over matter',
 ' It is possible that the infusoria under the microscope do the same',
 ' No one gave a thought to the older worlds of space as sources of human danger or thought of them only to dismiss the idea of life upon them as impossible or improbable',
 ' It is curious to recall some of the mental habits of those departed days',
 ' At most terrestrial men fa

In [349]:
tokens[:10]

['BOOK ONE THE COMING OF THE MARTIANS I',
 ' THE EVE OF THE WAR',
 ' No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than manâ\x80\x99s and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water',
 ' With infinite complacency men went to and fro over this globe about their little affairs serene in their assurance of their empire over matter',
 ' It is possible that the infusoria under the microscope do the same',
 ' No one gave a thought to the older worlds of space as sources of human danger or thought of them only to dismiss the idea of life upon them as impossible or improbable',
 ' It is curious to recall some of the mental habits of those departed days',
 ' At most terrestrial men fa

In [350]:
! rm book_text.csv

In [351]:
with open('book_text.csv', 'a+') as file:
    for sentence in tokens:
        file.write(sentence + '\n')

In [352]:
with open('book_text.csv') as file:
    lines = file.readlines()[:5]
print(lines[0])
print(lines[1])
print(lines[2])

BOOK ONE THE COMING OF THE MARTIANS I

 THE EVE OF THE WAR

 No one would have believed in the last years of the nineteenth century that this world was being watched keenly and closely by intelligences greater than man’s and yet as mortal as his own; that as men busied themselves about their various concerns they were scrutinised and studied perhaps almost as narrowly as a man with a microscope might scrutinise the transient creatures that swarm and multiply in a drop of water



In [509]:
data = TextLMDataBunch.from_csv('.', 'book_text.csv', text_cols=0, max_vocab=1000, min_freq=2)

In [510]:
data

TextLMDataBunch;

Train: LabelList (2434 items)
x: LMTextList
xxbos i turned xxunk xxunk towards the xxunk xxunk of xxmaj xxunk xxmaj park,xxbos i gave a xxunk of astonishment,xxbos xxmaj another xxunk tentacle xxunk the powder from the xxunk along a xxunk xxunk towards some xxunk that was hidden from me by the mound of xxunk dust,xxbos xxunk xxunk,xxbos xxmaj the last xxunk point in which the xxunk of these creatures xxunk from xxunk was in what one might have thought a very xxunk xxunk
y: LMLabelList
,,,,
Path: .;

Valid: LabelList (609 items)
x: LMTextList
xxbos xxmaj going on towards xxmaj xxunk the streets were quiet again,xxbos xxmaj six xxunk xxunk i xxunk and after a long xxunk six again,xxbos xxmaj about five o’clock the xxunk crowd in the station was xxunk excited by the opening of the line of xxunk which is almost xxunk closed between the xxmaj south - xxmaj xxunk and the xxmaj south - xxmaj western xxunk and the passage of carriage xxunk xxunk huge guns and carriages xxun

In [511]:
data.bptt = 3

In [512]:
data.train_ds[0]

(Text xxbos i turned xxunk xxunk towards the xxunk xxunk of xxmaj xxunk xxmaj park,
 EmptyLabel )

In [513]:
data.train_ds[1][0].data

array([  2,  13, 288,  12,   0,  11, 758])

In [514]:
data.valid_ds[1][0].data

array([  2,   5, 448,   0,   0,  13,   0,  10,  77,  12, 164,   0, 448,  81])

In [515]:
data.one_batch()[0].shape

torch.Size([64, 70])

In [516]:
x, y = data.one_batch()

In [517]:
x.shape, y.shape

(torch.Size([64, 70]), torch.Size([64, 70]))

In [518]:
x[0], y[0]

(tensor([ 11,   0,   0,  97, 250, 560, 761,  14,  58,   2, 561, 109,  15,   9,
           0,  11,   0,  13,  56,   0,  21,  18,  62,   2,   5,  30,  19, 200,
           0,  11,  12,  73, 275,   0,  10,  25,   0,  18,  53,  22,   0,  28,
         328,   0,  10,   0,   0,   2,   5,  47,   0,  19,   9, 232,   0,  32,
         131,  38,  64, 345,   9, 240,  28, 167,  38,  19, 117, 111,  54, 130]),
 tensor([  0,   0,  97, 250, 560, 761,  14,  58,   2, 561, 109,  15,   9,   0,
          11,   0,  13,  56,   0,  21,  18,  62,   2,   5,  30,  19, 200,   0,
          11,  12,  73, 275,   0,  10,  25,   0,  18,  53,  22,   0,  28, 328,
           0,  10,   0,   0,   2,   5,  47,   0,  19,   9, 232,   0,  32, 131,
          38,  64, 345,   9, 240,  28, 167,  38,  19, 117, 111,  54, 130, 124]))

In [519]:
len(data.vocab.itos)

1006

In [520]:
nv = len(data.vocab.itos)

In [521]:
nh = 64

In [522]:
bs = 64

In [523]:
class BasicLanguageModel(nn.Module):
     
    def __init__(self):
        super().__init__()
        self.i_h = nn.Embedding(nv, nh)
        self.h_h = nn.Linear(nh, nh)
        self.h_o = nn.Linear(nh, nv)
        self.bn = nn.BatchNorm1d(nh)
        self.h = torch.zeros(bs, nh).cuda()
        
    def forward(self, x):
        res = []
        h = self.h
        for i in range(x.shape[1]):
            h = h + self.i_h(x[:,i]) 
            h = F.relu(self.h_h(h))
            res.append(self.bn(h))
        self.h = h.detach()
        res = torch.stack(res, dim=1)
        res = self.h_o(res)
        return res

In [524]:
data.label_list

LabelLists;

Train: LabelList (2434 items)
x: LMTextList
xxbos i turned xxunk xxunk towards the xxunk xxunk of xxmaj xxunk xxmaj park,xxbos i gave a xxunk of astonishment,xxbos xxmaj another xxunk tentacle xxunk the powder from the xxunk along a xxunk xxunk towards some xxunk that was hidden from me by the mound of xxunk dust,xxbos xxunk xxunk,xxbos xxmaj the last xxunk point in which the xxunk of these creatures xxunk from xxunk was in what one might have thought a very xxunk xxunk
y: LMLabelList
,,,,
Path: .;

Valid: LabelList (609 items)
x: LMTextList
xxbos xxmaj going on towards xxmaj xxunk the streets were quiet again,xxbos xxmaj six xxunk xxunk i xxunk and after a long xxunk six again,xxbos xxmaj about five o’clock the xxunk crowd in the station was xxunk excited by the opening of the line of xxunk which is almost xxunk closed between the xxmaj south - xxmaj xxunk and the xxmaj south - xxmaj western xxunk and the passage of carriage xxunk xxunk huge guns and carriages xxunk wit

In [525]:
data.bptt = 20
data.batch_size = bs

In [526]:
learn = Learner(data, BasicLanguageModel(), metrics=accuracy)

In [527]:
learn.fit_one_cycle(20, max_lr=3e-2)

# TODO: try a GRU/LSTM